services:
  - type: web
    name: cropdoc-frontend
    env: static
    rootDir: .
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: cropdoc-backend
          envVarKey: RENDER_EXTERNAL_URL
